version: 2
updates:
- package-ecosystem: npm
  directory: "/web"
  schedule:
    interval: monthly
    time: "13:00"
    timezone: Europe/Brussels
  open-pull-requests-limit: 99
- package-ecosystem: npm
  directory: "/cli"
  schedule:
    interval: monthly
    time: "13:00"
    timezone: Europe/Brussels
  open-pull-requests-limit: 99
