version: 2
updates:
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: weekly
    time: "13:00"
    timezone: Europe/Brussels
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "13:00"
    timezone: Europe/Brussels
