version: "3.9"
services:
  db:
    image: mariadb:latest
    volumes:
      - dolos-db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: dolos
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails db:prepare && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - dolos-api-storage:/dolos/storage
      #- .:/dolos
    ports:
      - "3000:3000"
    environment:
      DOLOS_API_DATABASE_USERNAME: root
      DOLOS_API_DATABASE_PASSWORD: dolos
      DOLOS_API_DATABASE_HOST: db
    depends_on:
      - worker
  worker:
    build: .
    command: bash -c "bundle exec rails jobs:work"
    volumes:
      - dolos-api-storage:/dolos/storage
      - /var/run/docker.sock:/var/run/docker.sock
      #- .:/dolos
    environment:
      DOLOS_API_DATABASE_USERNAME: root
      DOLOS_API_DATABASE_PASSWORD: dolos
      DOLOS_API_DATABASE_HOST: db
    depends_on:
      - db
volumes:
  dolos-db-data:
  dolos-api-storage:
