name: Checks
on: [push]

jobs:
  install-deps:
    name: Install dependencies (Node ${{ matrix.node }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ["12", "14", "16"]
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - name: Cache Yarn dependencies
        id: cache-dependencies
        uses: actions/cache@v2
        with:
          path: |
            ${{ github.workspace }}/node_modules
            ${{ github.workspace }}/*/node_modules
          key: ${{ runner.os }}-node-${{ matrix.node }}-${{ hashFiles('/yarn.lock') }}
      - name: Yarn install
        if: steps.cache-dependencies.outputs.cache-hit != 'true'
        run: yarn install

  docs:
    name: "Docs: build"
    runs-on: ubuntu-latest
    needs: install-deps
    strategy:
      matrix:
        node: ["16"]
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - name: Fetch dependencies
        id: cache-dependencies
        uses: actions/cache@v2
        with:
          path: |
            ${{ github.workspace }}/node_modules
            ${{ github.workspace }}/*/node_modules
          key: ${{ runner.os }}-node-${{ matrix.node }}-${{ hashFiles('/yarn.lock') }}
      - name: Check if cache was hit
        if: steps.cache-dependencies.outputs.cache-hit != 'true'
        run: |
          echo "Should have hit cache"
          false
      - name: Build site
        run: |
          cd docs/
          yarn build

  cli-build-test:
    name: "CLI: build and test"
    runs-on: ubuntu-latest
    needs: install-deps
    strategy:
      matrix:
        node: ["12", "14", "16"]
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - name: Fetch dependencies
        id: cache-dependencies
        uses: actions/cache@v2
        with:
          path: |
            ${{ github.workspace }}/node_modules
            ${{ github.workspace }}/*/node_modules
          key: ${{ runner.os }}-node-${{ matrix.node }}-${{ hashFiles('/yarn.lock') }}
      - name: Check if cache was hit
        if: steps.cache-dependencies.outputs.cache-hit != 'true'
        run: |
          echo "Should have hit cache"
          false
      - name: Build and test
        run: |
          cd cli/
          yarn build
          yarn test

  cli-lint:
    name: "CLI: lint"
    runs-on: ubuntu-latest
    needs: install-deps
    strategy:
      matrix:
        node: ["16"]
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - name: Fetch dependencies
        id: cache-dependencies
        uses: actions/cache@v2
        with:
          path: |
            ${{ github.workspace }}/node_modules
            ${{ github.workspace }}/*/node_modules
          key: ${{ runner.os }}-node-${{ matrix.node }}-${{ hashFiles('/yarn.lock') }}
      - name: Check if cache was hit
        if: steps.cache-dependencies.outputs.cache-hit != 'true'
        run: |
          echo "Should have hit cache"
          false
      - name: Lint
        run: |
          cd cli/
          yarn lint

  web-build-test:
    name: "Web: build and test"
    runs-on: ubuntu-latest
    needs: install-deps
    strategy:
      matrix:
        node: ["12", "14", "16"]
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - name: Fetch dependencies
        id: cache-dependencies
        uses: actions/cache@v2
        with:
          path: |
            ${{ github.workspace }}/node_modules
            ${{ github.workspace }}/*/node_modules
          key: ${{ runner.os }}-node-${{ matrix.node }}-${{ hashFiles('/yarn.lock') }}
      - name: Check if cache was hit
        if: steps.cache-dependencies.outputs.cache-hit != 'true'
        run: |
          echo "Should have hit cache"
          false
      - name: Build
        run: |
          cd web/
          yarn build

  web-lint:
    name: "Web: lint"
    runs-on: ubuntu-latest
    needs: install-deps
    strategy:
      matrix:
        node: ["16"]
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - name: Fetch dependencies
        id: cache-dependencies
        uses: actions/cache@v2
        with:
          path: |
            ${{ github.workspace }}/node_modules
            ${{ github.workspace }}/*/node_modules
          key: ${{ runner.os }}-node-${{ matrix.node }}-${{ hashFiles('/yarn.lock') }}
      - name: Check if cache was hit
        if: steps.cache-dependencies.outputs.cache-hit != 'true'
        run: |
          echo "Should have hit cache"
          false
      - name: Lint
        run: |
          cd web/
          yarn lint
