name: Dolos-cli

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ["12", "14", "16"]
      fail-fast: false
    name: Test with Node ${{ matrix.node }}
    steps:
      - uses: actions/checkout@v1
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - name: Cache Yarn dependencies
        uses: actions/cache@v1
        with:
          path: ${{ github.workspace }}/node_modules
          key: ${{ runner.os }}-node-${{ matrix.node }}-node_modules-${{ hashFiles(format('{0}{1}', github.workspace, '/yarn.lock')) }}
          restore-keys: |
            ${{ runner.os }}-node-${{ matrix.node }}-node_modules-
      - name: Test
        run: |
          yarn install
          cd cli/
          yarn build
          yarn test --verbose
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: "16"
      - name: Cache Yarn dependencies
        uses: actions/cache@v1
        with:
          path: ${{ github.workspace }}/cli/node_modules
          key: ${{ runner.os }}-node-16-node_modules-${{ hashFiles(format('{0}{1}', github.workspace, '/cli/yarn.lock')) }}
          restore-keys: |
            ${{ runner.os }}-node-16-node_modules-
      - name: Lint
        run: |
          yarn install
          cd cli/
          yarn lint
