name: CLI
on:
  push:
    paths:
      - "cli/**/*"
      - "*.*"

jobs:
  # Install Dependencies
  install:
    uses: ./.github/workflows/dependencies.yml
  
  # Build
  build:
    name: Build 🔧
    runs-on: ubuntu-latest
    needs: install
    strategy:
      matrix:
        node: ["12", "14", "16"]
      fail-fast: false
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3

      - name: Setup Node 📚
        uses: actions/setup-node@v3.3.0
        with:
          node-version: ${{ matrix.node }}

      - name: Fetch Dependencies ⚡️
        id: cache-dependencies
        uses: actions/cache@v3
        with:
          path: |
            ${{ github.workspace }}/node_modules
            ${{ github.workspace }}/*/node_modules
          key: ${{ needs.install.outputs.cachekey }}

      - name: Check if cache was hit 🔎
        if: steps.cache-dependencies.outputs.cache-hit != 'true'
        run: |
          echo "Should have hit cache"
          false

      - name: Build 🔧
        run: |
          cd cli/
          yarn build --force
  
  # Lint
  lint:
    name: Lint 📏
    runs-on: ubuntu-latest
    needs: install
    strategy:
      matrix:
        node: ["16"]
      fail-fast: false
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3

      - name: Setup Node 📚
        uses: actions/setup-node@v3.3.0
        with:
          node-version: ${{ matrix.node }}

      - name: Fetch Dependencies ⚡️
        id: cache-dependencies
        uses: actions/cache@v3
        with:
          path: |
            ${{ github.workspace }}/node_modules
            ${{ github.workspace }}/*/node_modules
          key: ${{ needs.install.outputs.cachekey }}

      - name: Check if cache was hit 🔎
        if: steps.cache-dependencies.outputs.cache-hit != 'true'
        run: |
          echo "Should have hit cache"
          false

      - name: Lint 📏
        run: |
          cd lib/
          yarn lint