name: Docs
on:
  push:
    paths:
      - "docs/**/*"
      - "*.*"
      - ".github/workflows/*"

jobs:
  # Install Dependencies
  install:
    uses: ./.github/workflows/dependencies.yml

  # Build & test
  build-test:
    name: Build & Test 🔧
    runs-on: ubuntu-latest
    needs: install
    strategy:
      matrix:
        node: ["12", "14", "16"]
      fail-fast: false
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3

      - name: Setup Node 📚
        uses: actions/setup-node@v3.3.0
        with:
          node-version: ${{ matrix.node }}

      - name: Fetch Dependencies ⚡️
        id: cache-dependencies
        uses: actions/cache@v3
        with:
          path: |
            ${{ github.workspace }}/node_modules
            ${{ github.workspace }}/*/node_modules
          key: ${{ needs.install.outputs.cachekey }}

      - name: Check if cache was hit 🔎
        if: steps.cache-dependencies.outputs.cache-hit != 'true'
        run: |
          echo "Should have hit cache"
          false

      - name: Build 🔧
        run: |
          cd docs/
          yarn build

      - name: Deploy 🚀
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: |
          if [ -n "$KNOWN_HOSTS" ]; then
            cd docs/
            mkdir -p ~/.ssh
            echo "$SSH_KEY" > ~/.ssh/id_rsa
            chmod 600 ~/.ssh/id_rsa
            echo "$KNOWN_HOSTS" > ~/.ssh/known_hosts
            chmod 600 ~/.ssh/known_hosts
            rsync -glpPrtvz \
                  --delete  \
                  -e 'ssh -p 4840' \
                  .vuepress/dist/ \
                  dodona@dolos.ugent.be:docs
          else
            echo "Skipping deploy because secrets are not available"
          fi
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}
          KNOWN_HOSTS: ${{ secrets.KNOWN_HOSTS }}

  # Lint
  lint:
    name: Lint 📏
    runs-on: ubuntu-latest
    needs: install
    strategy:
      matrix:
        node: ["16"]
      fail-fast: false
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3

      - name: Setup Node 📚
        uses: actions/setup-node@v3.3.0
        with:
          node-version: ${{ matrix.node }}

      - name: Fetch Dependencies ⚡️
        id: cache-dependencies
        uses: actions/cache@v3
        with:
          path: |
            ${{ github.workspace }}/node_modules
            ${{ github.workspace }}/*/node_modules
          key: ${{ needs.install.outputs.cachekey }}

      - name: Check if cache was hit 🔎
        if: steps.cache-dependencies.outputs.cache-hit != 'true'
        run: |
          echo "Should have hit cache"
          false

      - name: Lint 📏
        run: |
          cd lib/
          yarn lint
