name: Dolos-web

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ["12", "14"]
      fail-fast: false
    name: Build with Node ${{ matrix.node }}
    steps:
      - uses: actions/checkout@v1
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - name: Cache Yarn dependencies
        uses: actions/cache@v1
        with:
          path: ${{ github.workspace }}/web/node_modules
          key: ${{ runner.os }}-node-${{ matrix.node }}-node_modules-${{ hashFiles(format('{0}{1}', github.workspace, '/web/yarn.lock')) }}
          restore-keys: |
            ${{ runner.os }}-node-${{ matrix.node }}-node_modules-
      - name: Test
        run: |
          cd web/
          yarn install
          yarn build
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Node
        uses: actions/setup-node@v1
      - name: Cache Yarn dependencies
        uses: actions/cache@v1
        with:
          path: ${{ github.workspace }}/web/node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles(format('{0}{1}', github.workspace, '/web/yarn.lock')) }}
          restore-keys: |
            ${{ runner.os }}-node_modules-
      - name: Lint
        run: |
          cd web/
          yarn install
          yarn lint
